### ISSUE TITLE
JSON Pointer reference parsing fails when pointing the root document

### ISSUE THREAD

**Issue by Viicos** [python-jsonschema/referencing#148]
While uncommon, I believe it is possible to have an empty JSON Pointer (i.e. `""`), referencing the root of the document (see [examples](https://datatracker.ietf.org/doc/html/rfc6901#section-5) in the RFC).

Here is a regression test:

```python
resource = Resource.opaque(contents={"foo": "baz"})
resolver = Registry().resolver()
assert resource.pointer("", resolver=resolver).contents == {"foo": "baz"}
```

Current behavior:

```sh
referencing.exceptions.PointerToNowhere: '' does not exist within {'foo': 'baz'}
```

**Comment by Julian** [comment]
Indeed, thanks for the report. This bug is somewhat hidden from "real life" I think given that `Resolver.lookup("#", ...)` already handles this when you use a pointer referred to by a fragment, but indeed you're correct that `.pointer()` needs to as well given it's public API. I've pushed a fix.

Out of curiosity given you're using that API, I assume you're writing a library or some thing using `referencing` and not simply using it alongside a JSON Schema implementation? Can you share anything about what you're working on just out of curiosity.

Thanks again.

**Comment by Viicos** [comment]
Thanks for the quick fix! In this case I wasn't directly using `referencing`, but got inspired by your JSON Pointer parsing implementation (will add credit in my codebase soon). I'm implementing the [JsonLogic](https://jsonlogic.com/) rule format in Python (repo can be found [here](https://github.com/Viicos/jsonlogic)), and it is possible to access data when evaluating a rule/expression:

```python
evaluate({">": [{"var": "/path_to/my_int"}, 2]}, data={"path_to": {"my_int": 2}})
```

And I support the JSON Pointer spec to specify the location of a variable.

---

While evaluation of such rules are not related to JSON Schema at all, I provide a [typechecking](https://jsonlogic.readthedocs.io/latest/usage/typechecking.html) mechanism, based on the JSON Schema format. I currently support a limited subset of the spec (i.e. no `anyOf`, etc) and I'm doing this "by hand", but this definitely relates to our previous discussion: https://github.com/python-jsonschema/referencing/issues/124

I'm currently exploring more of this with this project, and maybe in the future this could help implementing this "structured schema walker" :)

**Comment by Julian** [comment]
Got it, good info, and yes that sounds great!
