### ISSUE TITLE
Nested reference unresolvable when slash character ("/") in reference URI

### ISSUE THREAD

**Issue by AAriam** [python-jsonschema/referencing#164]
When two resources are added, where one resource references the other resource, the resource that is being referenced by the other resource becomes unresolvable when the referencing resource has a slash in its URI. For example, here is a function that gets the URIs of two resources, where one references the other, and tries to validate a data with a schema that references the second resource:
```python
def test_nested_resource_uri(source_resource_name: str, second_resource_name: str):
    # The source resource (being referenced by another resource)
    resource_source = referencing.Resource.from_contents(
       {"type": "string"},
       default_specification=referencing.jsonschema.DRAFT202012
    )
    # The referencing resource (referencing the source resource)
    resource_second = referencing.Resource.from_contents(
       {"$ref": source_resource_name},
       default_specification=referencing.jsonschema.DRAFT202012
    )
    reg = referencing.Registry().with_resources(
        [
            (source_resource_name, resource_source), 
            (second_resource_name, resource_second)
        ]
    )
    jsonschema.validate(
        "text",
        schema={"$ref": second_resource_name},
        registry=reg
    )
```

Now, this
```python
test_nested_resource_uri(source_resource_name="def/source", second_resource_name="def/second")
```
raises an error:
```shell
_WrappedReferencingError: Unresolvable: def/source
```
while this
```python
 test_nested_resource_uri(source_resource_name="def/source", second_resource_name="def-second")
```
works.

Environment:
```
referencing == 0.35.1
jsonschema == 4.23.0
```

**Comment by Julian** [comment]
This has a bit more to do with the fact that you're relying on some undefined base URI -- specifically your root document (in this case the one you're calling `"def/second"`) has only a relative URI, so you're relying on an internal base URI.

I forget whether the spec says this is completely not allowed or just discouraged, but I'm pretty sure it's not *en*couraged. 

But in particular, it means that when we resolve `def/second` and then resolve `def/source`, relative to `def/second` that means we're trying to resolve `def/def/source`, which indeed does not exist in that registry. You either need to use an absolute URI, or to add a trailing slash to make the relative URI resolve to `def/source` instead of `def/def`.

The reason your other example works is that `def/source` relative to `def-second` is just `def/source`, so that will be found fine.

I'm going to close this as it seems everything is working as expected, but if the above explanation is unclear or you disagree feel free to follow up!

**Comment by AAriam** [comment]
Hi @Julian,

Thanks a lot for the explanation!
