### ISSUE TITLE
Relative URL paths as $refs

### ISSUE THREAD

**Issue by jsignell** [python-jsonschema/referencing#80]
I am trying to replace `RefResolver` with `Registry` in pystac (https://github.com/stac-utils/pystac/pull/1215) and cannot get relative paths to work. I wrote a retrieve function that should make the relative schema URIs  absolute with respect to the location of the base schema, but it seems like the `../..` are getting stripped off. 

Here is an example of the type of schemas I am working with: https://raw.githubusercontent.com/radiantearth/stac-spec/v0.8.1/collection-spec/json-schema/collection.json. 

`"../../catalog-spec/json-schema/catalog.json"` for instance is just `"catalog-spec/json-schema/catalog.json"` within my `retrieve` function.

This is potentially similar to #70, but these refs are not prefixed by `file` so _I think_ this style of `ref` is supposed to be legit

**Comment by Julian** [comment]
I (obviously in a minute or two) haven't looked completely carefully, but initially, those indeed *don't* look legit for similar reasons! It's ambiguous what you mean when writing that, whether it's relative to the path of the file itself or whether (the *more* likely case) that it's relative to the working directory of the process!

You likely should change to use some URI scheme with proper relative path support, but I'd have to take a closer look to be sure.

**Comment by jsignell** [comment]
As a follow-up: is the issue that the `$id` is not a URL? If so then this might only be an issue with older versions of the spec since later versions specify the `$id` as a real URL: https://schemas.stacspec.org/v1.0.0/collection-spec/json-schema/collection.json

**Comment by Julian** [comment]
> As a follow-up: is the issue that the $id is not a URL?

I have to remind myself what the spec says honestly, what's going on here has to do with establishing a base URL basically -- and referencing has no way of knowing what base URL you mean (even though you obviously have one in mind, a base URL of the file path to the file you're using). My recollection is that yeah the JSON Schema says `$id` of the root document is supposed to be an absolute URI, but I forget and have to remind myself, it's been a bit since I wrote referencing even :D

> Is there a recommendation for how to work with relative refs?

If I recall correctly from the other issue, the "hacky" way to proceed down this path regardless of whether it's allowed is, in `retrieve`, to ignore that you get an absolute path and regardless join it to your schema directory path. But I have to check again to see if there's an even better recommendation, or better something consistent with the spec.

And of course I could entirely be misremembering, so I'll leave this open anyhow to see if I've led you astray.

**Comment by jsignell** [comment]
Ok it looks like just fixing up the `$id` so that it is a url did the trick! After I did that the rel refs worked just fine!
